window.TRYCKTRACK_QUESTION_BANK = (window.TRYCKTRACK_QUESTION_BANK || []).concat([
  {
    "id": "enare-2024-001",
    "number": 1,
    "stem": "Uma paciente de 60 anos foi internada para investigação de anemia associada a déficit cognitivo. O médico percebeu lentidão de raciocínio e redução da capacidade executiva. A paciente estava atenta e cooperando com o examinador quando se queixou de parestesias (dormência e queimação) simétricas em ambos os membros inferiores. Em relação à anemia, havia macrocitose e reticulocitopenia. O nível de vitamina B12 sérica foi 125 pg/mL (normal: acima de 200 pg/mL).\nDiante desse quadro clínico, além da investigação da causa da anemia, deve-se proceder à reposição:",
    "options": {
      "A": "oral de cianocobalamina (1000 microgramas por dia) e manutenção da mesma dose uma vez por mês;",
      "B": "de cianocobalamina parenteral (1000 microgramas por dia) e manutenção da mesma dose por via oral a cada mês;",
      "C": "de cianocobalamina intramuscular (1000 microgramas por dia) e posterior injeção intramuscular uma vez por semana até reavaliação dos sintomas e investigação da causa;",
      "D": "de hidroxicobalamina parenteral ou oral três vezes por semana seguida da dose de 1000 microgramas, uma vez por semana, para o resto da vida;",
      "E": "de hidroxicobalamina parenteral (1000 microgramas por dia) até a mitigação dos sintomas."
    },
    "answer": "C",
    "area": "Hematologia",
    "assunto": "Anemias macrocíticas",
    "topico": "Anemia megaloblástica",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-002",
    "number": 2,
    "stem": "Após o início de tratamento antirretroviral (TARV) há 1 mês, um paciente com síndrome consumptiva, candidíase e diarreia crônica foi internado por outras manifestações. O grupo de residentes da clínica médica percebeu, durante os primeiros três dias de internação, febre vespertina, linfadenomegalias cervicais e axilares com fistulização e constipação intestinal com cólicas abdominais. Os exames demonstraram anemia e VHS e PCR elevados, bem como imagens reticulonodulares difusas e bilaterais em ambos os hemitóraces. As tomografias reforçaram os infiltrados reticulonodulares com linfadenomegalias mediastinais com centro necrótico, além de linfadenomegalias mesentéricas com espessamento de íleo distal. O paciente piorou clinicamente, apresentando-se prostrado e com hipoxemia no 4º dia de internação. A contagem de linfócitos CD4 no início do tratamento era de 45 células/mm³ e a PPD (prova tuberculínica anérgica) era 0 mm.\nDiante do exposto, a conduta mais adequada é:",
    "options": {
      "A": "suspender a TARV até finalizar a investigação para infecções intestinais relacionadas ao HIV;",
      "B": "proceder à biópsia de linfonodo por provável diagnóstico de linfoma;",
      "C": "iniciar tratamento empírico para tuberculose e micobactérias atípicas e prescrever procinéticos e laxativos;",
      "D": "realizar biópsia de linfonodo e coleta de escarro para análise de baciloscopia, teste rápido molecular para tuberculose e cultura para micobactéria; suspender a TARV e avaliar início de corticoide;",
      "E": "manter a TARV e acrescentar corticoide até o final da investigação, devido a reação imune."
    },
    "answer": "E",
    "area": "Infectologia",
    "assunto": "HIV/Aids",
    "topico": "Infecções oportunistas",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-003",
    "number": 3,
    "stem": "Durante o atendimento ambulatorial, José, de 68 anos, queixou-se de dor toracolombar de intensidade moderada, constante, iniciada há 3 semanas. Foi associada a dormência nas duas pernas, havendo piora da dor quando ele ficava muito tempo em pé e melhora quando se sentava ou se deitava. O paciente já estava em tratamento para diabetes mellitus há 10 anos, com elevação recente da dose de metformina para 2 g/dia. Segundo ele, a glicemia estava bem controlada, mas o tabagismo e o alcoolismo persistiam (75 maços x ano e 40 g de álcool por dia). Na anamnese dirigida, revelou-se constipação de início recente, sem mudança do volume ou consistência das fezes. Não houve qualquer outra queixa ou sintoma relatado. No exame físico, notam-se dor à palpação da musculatura paravertebral bilateralmente, bem como dor em queimação agravada em flexão de quadril e coxa. Sinais de Lasègue e Kernig positivos bilateralmente. O restante do exame físico não mostrou alterações.\nConsiderando o quadro exposto, é correto afirmar que:",
    "options": {
      "A": "uma conduta mais agressiva deve ser adotada, com investigação de tumores devido à idade e ao tabagismo, apesar de se tratar de uma dor lombar aguda;",
      "B": "a ressonância de coluna torácica e lombar é obrigatória devido à localização da dor, ao tempo de acometimento e aos sinais neurológicos;",
      "C": "radiografia de tórax, VHS, proteína C-reativa e hemograma devem ser solicitados, mas pode ser necessário solicitar também uma ressonância nuclear magnética (RNM) de coluna torácica e lombar se as medidas comportamentais e analgesia não melhorarem;",
      "D": "a dor lombar em pessoa acima de 50 anos deve ser sempre investigada, independentemente dos sintomas e sinais associados. O principal exame é a ressonância nuclear magnética (RNM) de coluna lombar com contraste venoso;",
      "E": "os sinais de alarme associados a dor lombar subaguda ou crônica (respectivamente, 4 a 12 semanas e mais de 12 semanas) em indivíduos com mais de 50 anos são desnecessários para indicação de exame específico, pois todos esses pacientes devem ter exame de imagem."
    },
    "answer": "B",
    "area": "Ortopedia",
    "assunto": "Ortopedia Geral",
    "topico": "Doenças da coluna vertebral",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-004",
    "number": 4,
    "stem": "Um rapaz de 18 anos foi atendido no ambulatório de clínica médica para acompanhamento de lúpus eritematoso sistêmico com nefrite e cardite. Estava em bom estado geral após 3 pulsoterapias com corticoide e ciclofosfamida, mas deveria fazer nova dose de corticoide sistêmico naquele mês. No entanto, apresentava lesões hiperemiadas com vesículas e algumas pústulas em dermátomos oftálmico e maxilar da hemiface direita. A impressão do médico foi de herpes-zóster.\nA conduta adequada para esse caso é:",
    "options": {
      "A": "prescrição de aciclovir oral 800 mg, 5 vezes ao dia, por 14 dias, e encaminhar o paciente para casa;",
      "B": "profilaxia dos contactantes domiciliares e hospitalares com a vacina contra varicela-zóster, independentemente do estado de imunização, do estado imunológico e do tempo de exposição;",
      "C": "internação hospitalar para isolamento respiratório e de contato, prescrição de aciclovir parenteral e acompanhamento de complicações pelo herpes-zóster disseminado;",
      "D": "prescrição de aciclovir parenteral apenas se o rash e as vesículas tiverem iniciado há menos de 72 horas. Caso contrário, fazer apenas a profilaxia dos contactantes com vacina e do paciente com antibiótico devido à alta prevalência de infecção bacteriana secundária;",
      "E": "internação hospitalar em quarto com pressão negativa e precauções de contato como máscara cirúrgica, capote, luva, gorro e óculos para toda a equipe assistencial. O aciclovir de 800 mg pode ser feito de forma oral, 5 vezes ao dia, por 7 a 10 dias ou até a alta hospitalar."
    },
    "answer": "C",
    "area": "Reumatologia",
    "assunto": "Doenças autoimunes do tecido conjuntivo",
    "topico": "Lúpus Eritematoso Sistêmico (LES)",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-005",
    "number": 5,
    "stem": "Uma paciente de 49 anos foi internada na enfermaria de clínica médica por quadro de síndrome consumptiva, ascite e fraqueza em membros inferiores. A paciente conta que tudo começou 1 ano antes com dormência nas pernas ascendendo até o meio da perna e posterior redução de força em membros inferiores. Naquela época, houve turvação visual e cefaleia. Com aproximadamente 4 meses de sintomas, sem limitação para trabalhar e realizar as tarefas da vida diária, a cefaleia e a turvação visual ficaram mais proeminentes. Segundo a paciente, foram realizados diversos exames (ressonância de crânio, coluna cervical e lombar), sem evidência de alterações. A pressão do liquor estava alta, motivando o uso de acetazolamida por 8 meses (até a internação). No dia da internação, pôde-se observar hepatoesplenomegalia, ascite de grande volume, déficit sensitivo-motor distal em membros inferiores com hiporreflexia, fenômeno de Raynaud, cistos em tireoide (ultrassom confirmando e uso prévio de levotiroxina) e lesões cutâneas hipercrômicas. Outros exames demonstraram lesões osteoescleróticas em esterno, derrame pleural e pericárdico e padrão de polirradiculoneuropatia desmielinizante crônica.\nA conduta adequada para o quadro é:",
    "options": {
      "A": "dosagem de fator reumatoide, fator antinuclear, anti-Scl-70, anticentrômero e pulsoterapia por provável doença do tecido conjuntivo indiferenciada ou sobreposição de lúpus com esclerodermia em evolução grave;",
      "B": "dosagem de eletroforese de proteínas séricas e urinárias com imunofixação em busca de pico monoclonal;",
      "C": "biópsia de gordura abdominal em busca de proteína amiloide;",
      "D": "biópsia de peritônio se o gradiente soro-ascite for menor que 1,1;",
      "E": "punção aspirativa de cisto tireoidiano."
    },
    "answer": "B",
    "area": "Hematologia",
    "assunto": "Gamopatias monoclonais",
    "topico": "Classificação das gamopatias monoclonais",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-006",
    "number": 6,
    "stem": "Uma mulher de 20 anos se queixa de edema generalizado iniciado há 3 semanas, que evoluiu com piora progressiva. Relata hiporexia e astenia nesse período. Desconhece ser portadora de doenças atuais ou prévias e não faz uso de quaisquer medicamentos ou drogas. Ao exame físico, PA: 160 x 90 mmHg, FC: 97 bpm, FR: 22 ipm, SpO2 98% (em ar ambiente). As mucosas estão hipocoradas, ictéricas e hidratadas. Há edema na face, pálpebras, parede abdominal e membros inferiores. Há também ascite e síndrome de derrame pleural.\nExames de laboratório: sangue: Hb: 7,0 g/dL; Hct: 24%; VCM: 98 fL; HCM: 31 pg; CHCM: 32 g/dL; RDW: 18, 3%; leucócitos: 3.400/mm³; neutrófilos segmentados: 1.500/mm³; linfócitos: 700/mm³; Plq.: 201.000/mm³; PCR: 28m g/dL; FAN reagente: 1:320 padrão nuclear homogêneo; anti-DNA reagente; anti-SSA reagente; anti-SSB reagente; anti-Sm reagente; ANCA não reagente; C3: 43 mg/dL (90-170 mg/dL); C4: 10 mg/dL (VR: 12-36 mg/dL); exame de urina: densidade 1.020; pH 6,0; nitrito negativo; proteínas ++++; hemoglobina ++; 4 piócitos/campo, 145 hemácias/campo; presença de cilindros hemáticos. Para investigação da anemia apresentada pela paciente, são solicitados os seguintes exames: LDL: 1150 UI/L (VR: 120-246 UI/L); BT: 4,2 mg/dL; BD: 0,4 mg/dL; reticulócitos: 18%, Coombs direto positivo; ferro sérico: 52 mcg/dL (VR: 65-175 mcg/dL); ferritinemia 650 ng/mL (VR: 10-291 ng/mL); capacidade total de ligação do ferro: 200 mcg/dL (250-425 mcg/dL).\nA conduta imediata mais adequada para o tratamento da anemia é:",
    "options": {
      "A": "administração de eritropoetina;",
      "B": "administração de corticoide;",
      "C": "reposição de ferro parenteral;",
      "D": "hemotransfusão;",
      "E": "prescrição de hidroxicloroquina oral."
    },
    "answer": "B",
    "area": "Reumatologia",
    "assunto": "Doenças autoimunes do tecido conjuntivo",
    "topico": "Lúpus Eritematoso Sistêmico (LES)",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-007",
    "number": 7,
    "stem": "A pneumonia em organização criptogênica (POC) tem sua forma idiopática de pneumonia em organização, anteriormente chamada de bronquiolite obliterante com pneumonia em organização (BOOP). É uma doença pulmonar intersticial difusa decorrente de lesão na parede alveolar tipicamente caracterizada por infiltrados pulmonares periféricos e difusos com áreas de preenchimento alveolar e responsividade a terapia sistêmica com glicocorticoides. A manifestação clínica é de uma pneumonia subaguda ou de difícil resolução, com tosse pouco produtiva, dispneia, febre baixa e fraqueza ou cansaço. No entanto, há diversas condições autoimunes, pneumonias de hipersensibilidade e efeitos colaterais que devem ser excluídos para que a POC seja dada como idiopática.\nEm uma análise mais profunda sobre a POC, o quadro descrito acima pode indicar pneumonia em organização caso se verifique(m):",
    "options": {
      "B": "aspecto tomográfico reticulonodular difuso em paciente com dispneia importante iniciada há 1 semana;",
      "A": "paciente com tosse, febre e dispneia há 3 semanas e imagem apical fibrótica e cavitação adjacente;",
      "C": "aspecto radiográfico de consolidação lobar em paciente com febre alta de início recente;",
      "D": "aspecto tomográfico de consolidação irregular do espaço aéreo, opacidades em vidro fosco e pequenas opacidades nodulares em paciente usuário de cocaína;",
      "E": "aspecto tomográfico com opacidades evanescentes, bronquiectasias e achados relacionados a impactação mucoide e obstrução brônquica em paciente com eosinofilia e broncoespasmo."
    },
    "answer": "D",
    "area": "Pneumologia",
    "assunto": "Pneumopatias Intersticiais, Hipertensão Pulmonar, Bronquiectasias e Pneumotórax Espontâneo",
    "topico": "Pneumopatias Intersticiais",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-008",
    "number": 8,
    "stem": "Um homem de 31 anos, previamente saudável, apresenta-se com uma história de 2 anos de disfagia intermitente, principalmente para alimentos sólidos. Relatou 2 episódios de impactação alimentar, com necessidade de endoscopia digestiva alta de urgência. Estava em uso de esomeprazol (40 mg ao dia) há 6 meses, sem melhora significativa dos sintomas de disfagia. Realizou recentemente nova endoscopia, em que a biópsia foi compatível com esofagite eosinofílica, sem estenose esofágica. Foi orientado a restringir alimentos que pudessem estar associados com essa forma de esofagite. Contudo, não houve resposta satisfatória.\nNesse caso, a estratégia de intervenção mais adequada é:",
    "options": {
      "A": "associar sucralfato antes das refeições e à noite, antes de deitar;",
      "B": "trocar esomeprazol por outro bloqueador da bomba de prótons;",
      "C": "encaminhar para tratamento com terapia biológica específica;",
      "D": "associar um procinético (como domperidona) antes das refeições;",
      "E": "associar um esteroide tópico (como fluticasona ou budesonida) por via oral."
    },
    "answer": "E",
    "area": "Gastroenterologia",
    "assunto": "Esôfago",
    "topico": "Esofagites Não Pépticas",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-017",
    "number": 17,
    "stem": "Um paciente de 45 anos, sem doenças prévias, desenvolveu enfermidade de instalação súbita e progressiva com quadro de náuseas, vômitos, diarreia e dor abdominal. Logo após, queixou-se de cefaleia, vertigem e tontura. Foi internado na emergência, onde foi iniciada hidratação venosa e administração de sintomáticos. Entretanto, 3 horas depois começou a apresentar visão turva, ptose palpebral, diplopia, disfagia, disartria, boca seca e fraqueza muscular simétrica, acometendo com maior intensidade os membros superiores, sem perda da sensibilidade. Notaram-se hipotensão sem taquicardia e retenção urinária. Cerca de 6 horas após a internação, evoluiu para paralisia flácida motora descendente, associada a comprometimento autonômico disseminado. Durante todo esse período, o paciente se manteve consciente. A fraqueza muscular descendente afetou os músculos do tronco e dos membros, levando a dispneia, insuficiência respiratória e tetraplegia flácida. Foi necessária a transferência do paciente para o CTI, com instalação de tubo orotraqueal e ventilação mecânica, além de rotinas terapêuticas para pacientes graves.\nO diagnóstico mais provável é:",
    "options": {
      "A": "meningite por Haemophilus influenzae;",
      "B": "síndrome de Guillain-Barré;",
      "C": "doença de Lyme;",
      "D": "infecção pelo Clostridium botulinum;",
      "E": "raiva."
    },
    "answer": "D",
    "area": "Infectologia",
    "assunto": "Infecções bacterianas",
    "topico": "Difteria",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-018",
    "number": 18,
    "stem": "Um paciente de 22 anos apresentou quadro clínico com início abrupto de febre, cefaleia, mialgia, anorexia, náuseas e vômitos. Foi avaliado na UPA e liberado com prescrição de sintomáticos. Vinte e quatro horas depois, apresentou diarreia, artralgia, dor ocular, fotofobia e hemorragia conjuntival, além de tosse. Foi internado, recebendo hidratação venosa e sintomáticos venosos. Foram solicitados exames complementares, com os seguintes resultados: leucocitose, neutrofilia e desvio à esquerda, plaquetopenia, aumento de ureia e creatinina, CPK elevada, baixa densidade urinária, proteinúria, hematúria microscópica e leucocitúria.\nFoi então iniciada antibioticoterapia com sulfametoxazol + trimetoprima. Logo a seguir, o paciente apresentou exantema, eritema macular, papular purpúrico, distribuídos no tronco ou na região pré-tibial. USG exibiu hepatomegalia, esplenomegalia e linfadenopatia. Na ocasião, reclamou de intensa mialgia, principalmente em região lombar e nas panturrilhas.\nApesar do uso de antibiótico, não apresentou melhora, com evolução para tríade insuficiência renal, icterícia rubínica e hemorragia pulmonar discreta (síndrome de Weil). Foi intubado e no CTI iniciou penicilina G cristalina em dose plena e cuidados intensivos. Após 10 dias, apresentou melhora clínica, sendo transferido para enfermaria até concluir seu tratamento.\nA doença descrita acima é:",
    "options": {
      "A": "febre maculosa;",
      "B": "endocardite bacteriana;",
      "C": "leptospirose;",
      "D": "dengue hemorrágica;",
      "E": "infecção urinária por pseudomonas aeruginosa."
    },
    "answer": "C",
    "area": "Infectologia",
    "assunto": "Infecções bacterianas",
    "topico": "Difteria",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-019",
    "number": 19,
    "stem": "Um homem de 50 anos em tratamento para hepatite C, com cirrose hepática compensada CHILD PUGH A, tem histórico de falha terapêutica com uso prévio de antivirais de ação direta. O médico assistente do serviço de atenção especializada prescreveu um novo esquema terapêutico, recomendado pelo Ministério da Saúde.\nO esquema prescrito foi:",
    "options": {
      "A": "sofosbuvir/velpastavir/ribavirina por 24 semanas;",
      "B": "sofosbuvir/daclatasvir por 12 semanas;",
      "C": "sofosbuvir/pibrentasvir + glecaprevir por 12 semanas;",
      "D": "sofosbuvir/velpastavir por 12 semanas;",
      "E": "sofosbuvir/ribavirina por 24 semanas."
    },
    "answer": "A",
    "area": "Infectologia",
    "assunto": "Outras doenças infecciosas",
    "topico": "Doença de Chagas",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-020",
    "number": 20,
    "stem": "Mulher de 65 anos procura o gastroenterologista com queixas de astenia, prurido palmar e plantar e elevação de fosfatase alcalina (1005 UI/ml) e Gama GT (1200 UI/ml). As enzimas hepáticas TGO e TGP estão elevadas (300 e 250 UI/ml, respectivamente) e a bilirrubina total é de 6,0 mg/dl, às custas da bilirrubina direta. Apresenta plaquetopenia de 85.000/mm³, e a ultrassonografia de abdômen aponta alterações compatíveis com doença parenquimatosa crônica do fígado, sem dilatação das vias biliares intra e extra-hepáticas e vesícula biliar anecoica.\nA principal hipótese diagnóstica para o caso e o exame complementar a ser solicitado são, respectivamente:",
    "options": {
      "A": "hepatite colestática autoimune; FAN e antimúsculo liso;",
      "B": "colangite esclerosante primária; CPER e P-Anca;",
      "C": "colangite biliar primária; anti-LKM1;",
      "D": "colangite biliar primária; antimitocôndria;",
      "E": "hepatite medicamentosa; FAN e antimúsculo liso."
    },
    "answer": "D",
    "area": "Hepatologia",
    "assunto": "Outras Hepatopatias",
    "topico": "Colangite Biliar Primária (CBP)",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-021",
    "number": 21,
    "stem": "Um homem de 64 anos de idade, saudável, agricultor, apresenta-se no consultório com uma lesão cutânea que ele notou há cerca de 6 meses. A lesão está localizada no dorso da mão direita e tem crescido lentamente. O paciente relata que a área está um pouco dolorosa e pruriginosa. Ao exame físico, observa-se uma lesão de 1,2 cm de diâmetro, de cor acastanhada, bordas irregulares, e com algumas áreas de ulceração, e há linfadenomegalia palpável na axila.\nCom base na descrição clínica e no exame físico, as melhores propostas diagnóstica e terapêutica para esse paciente são, respectivamente:",
    "options": {
      "A": "carcinoma basocelular; tratamento com crioterapia;",
      "B": "queratoacantoma; tratamento com antibioticoterapia;",
      "C": "dermatofibroma; tratamento com observação e seguimento;",
      "D": "carcinoma espinocelular; tratamento com eletrocoagulação e curetagem;",
      "E": "melanoma maligno; tratamento com excisão cirúrgica ampla e avaliação do linfonodo."
    },
    "answer": "E",
    "area": "Dermatologia",
    "assunto": "Câncer de pele",
    "topico": "Melanoma",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-022",
    "number": 22,
    "stem": "Um homem de 47 anos de idade, fumante há 30 anos e com histórico de consumo de bebidas alcoólicas destiladas, apresenta uma úlcera dolorosa na língua há 3 meses. Relata que a lesão não cicatriza e está aumentando de tamanho. Além disso, nota dificuldade para engolir e dor referida no ouvido. Ao exame físico, observa-se uma úlcera irregular na borda lateral da língua, com margens endurecidas e base infiltrada. Não há linfonodos cervicais palpáveis.\nO diagnóstico provável e o tratamento inicial mais adequado para esse paciente são, respectivamente:",
    "options": {
      "A": "adenoma; ressecção com anestesia local;",
      "B": "candidíase oral; iniciar tratamento antifúngico tópico;",
      "C": "ulceração traumática; recomendações de higiene oral rigorosa e acompanhamento;",
      "D": "líquen plano oral; encaminhar para biópsia e tratamento com corticosteroides tópicos;",
      "E": "carcinoma espinocelular; biópsia da lesão, estadiamento e tratamento cirúrgico."
    },
    "answer": "E",
    "area": "Cirurgia Geral",
    "assunto": "Temas Gerais em Cirurgia",
    "topico": "Princípios da Cirurgia Oncológica",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-023",
    "number": 23,
    "stem": "Um adolescente de 16 anos foi admitido no pronto-socorro após queda de motocicleta. Ele estava lúcido e com sinais vitais estáveis. Realizou-se uma tomografia computadorizada do abdômen, que mostrou uma laceração esplênica grau II. Optou-se por um tratamento conservador inicial com monitoramento em unidade de terapia intensiva. Após 24 horas de internação, o paciente apresentou uma queda súbita na pressão arterial, aumento da frequência cardíaca e sinais de irritação peritoneal. Uma nova TC de abdômen mostrou aumento significativo do hemoperitônio e sinais de ruptura esplênica adicional.\nDiante desse quadro, a conduta mais apropriada para esse paciente é:",
    "options": {
      "A": "indicar a cirurgia de Warren;",
      "B": "realizar uma embolização seletiva da artéria esplênica;",
      "C": "transferi-lo para a sala de cirurgia para uma esplenectomia de emergência;",
      "D": "continuar com o manejo conservador e aumentar a frequência de monitoramento hemodinâmico;",
      "E": "administrar fluidos intravenosos e realizar a transfusão sanguínea, mantendo o paciente sob observação."
    },
    "answer": "C",
    "area": "Cirurgia Geral",
    "assunto": "Trauma",
    "topico": "Trauma Abdominal e Pélvico",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-024",
    "number": 24,
    "stem": "Pedro Paulo, um homem de 41 anos, foi admitido no pronto-socorro após sofrer queimaduras extensas em um incêndio no seu local de trabalho. Ele apresentava queimaduras de segundo grau que cobriam aproximadamente 45% de sua superfície corporal total (SCT). O paciente pesava 70 kg e estava consciente e lúcido, mas sentia dor intensa e desconforto. Os sinais vitais eram: frequência cardíaca: 120 bpm; pressão arterial de 100/60 mmHg; frequência respiratória de 24 ipm e saturação de oxigênio de 94% em ar ambiente. Seu médico decidiu iniciar a reanimação hídrica imediatamente.\nA melhor abordagem inicial para a reanimação hídrica de Pedro Paulo é:",
    "options": {
      "A": "administrar 2 ml/kg/%SCT de solução de Ringer Lactato nas primeiras 24 horas, dividindo o volume total igualmente ao longo do período;",
      "B": "administrar 8 ml/kg/%SCT de solução cristaloide de NaCl a 0,9% nas primeiras 24 horas, com um ajuste para cada %SCT adicional acima de 50%;",
      "C": "administrar 6 ml/kg/%SCT de solução de Ringer Lactato nas primeiras 24 horas, com um ajuste de 10% para cada grau adicional de queimadura acima do segundo grau;",
      "D": "administrar 4 ml/kg/%SCT de solução de Ringer Lactato nas primeiras 24 horas, dividindo o volume total em duas metades: uma nas primeiras 8 horas e a outra nas 16 horas seguintes;",
      "E": "administrar 4 ml/kg/%SCT de solução de colóide de albumina nas primeiras 24 horas, dividindo o volume total em duas metades: uma nas primeiras 8 horas e a outra nas 16 horas seguintes."
    },
    "answer": "D",
    "area": "Cirurgia Geral",
    "assunto": "Queimaduras e Trauma Elétrico",
    "topico": "Atendimento Inicial às Vítimas de Queimadura",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-041",
    "number": 41,
    "stem": "Uma adolescente de 12 anos apresenta pelos espessos e esparsos em genitália e mamas/mamilos aumentados, sem contorno definido.\nÉ correto afirmar que:\n(A) a adolescente tem o desenvolvimento puberal adequado para a sua idade;\n(B) a adolescente tem o desenvolvimento puberal atrasado para a sua idade;\n(C) o diagnóstico de pubarca precoce deve ser investigado;\n(D) o diagnóstico de telarca precoce deve ser investigado;\n(E) os dados apresentados não permitem avaliação do desenvolvimento puberal.",
    "options": {
      "A": "a adolescente tem o desenvolvimento puberal adequado para a sua idade",
      "B": "a adolescente tem o desenvolvimento puberal atrasado para a sua idade",
      "C": "o diagnóstico de pubarca precoce deve ser investigado",
      "D": "o diagnóstico de telarca precoce deve ser investigado",
      "E": "os dados apresentados não permitem avaliação do desenvolvimento puberal."
    },
    "answer": "A",
    "area": "Pediatria",
    "assunto": "Endocrinologia pediátrica",
    "topico": "Desordens do Desenvolvimento Sexual (DDS)",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-042",
    "number": 42,
    "stem": "Um recém-nascido de 21 dias, com idade gestacional de 32 semanas, peso de nascimento de 1.600 g, está internado na UTI neonatal com sépsis, em suporte ventilatório e hemodinâmico.\nA vacinação do paciente deve:\n(A) ocorrer de acordo com sua idade corrigida;\n(B) ocorrer imediatamente para estimulação imunológica;\n(C) ser realizada quando a criança tiver peso acima de 3 kg;\n(D) ser realizada após a alta hospitalar;\n(E) ser realizada durante a internação, sem vacinas com vírus vivos.",
    "options": {
      "A": "ocorrer de acordo com sua idade corrigida",
      "B": "ocorrer imediatamente para estimulação imunológica",
      "C": "ser realizada quando a criança tiver peso acima de 3 kg",
      "D": "ser realizada após a alta hospitalar",
      "E": "ser realizada durante a internação, sem vacinas com vírus vivos."
    },
    "answer": "D",
    "area": "Pediatria",
    "assunto": "Puericultura",
    "topico": "Imunizações/Vacinação",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-043",
    "number": 43,
    "stem": "Um lactente de 10 meses apresentou febre alta (39 °C) e coriza hialina por 3 dias. No quarto dia de doença, 12 horas após o último pico febril, surge exantema maculopapular em tronco que se dissemina para os membros. Ao exame, apresenta discreta hiperemia de orofaringe, linfonodos cervicais sem características inflamatórias e exantema maculopapular eritematoso difuso.\nDiante desse quadro, o diagnóstico correto é:\n(A) escarlatina;\n(B) sarampo;\n(C) varicela;\n(D) rubéola;\n(E) exantema súbito.",
    "options": {
      "A": "escarlatina",
      "B": "sarampo",
      "C": "varicela",
      "D": "rubéola",
      "E": "exantema súbito."
    },
    "answer": "E",
    "area": "Pediatria",
    "assunto": "Infectologia Pediátrica",
    "topico": "Doenças exantemáticas",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-044",
    "number": 44,
    "stem": "Os pais de um escolar em tratamento de rinite alérgica com corticoide nasal procuraram o posto de saúde para aplicação da vacina HPV (papilomavírus humano).\nEm vista do quadro apresentado, o agente do posto de saúde deverá:\n(A) orientar os pais a vacinarem a criança após o término do tratamento;\n(B) suspender a medicação por 7 dias após a vacinação;\n(C) vacinar a criança com as orientações habituais;\n(D) vacinar a criança com a dose dobrada da vacina;\n(E) vacinar a criança, advertindo quanto à possibilidade de reações vacinais mais intensas.",
    "options": {
      "A": "orientar os pais a vacinarem a criança após o término do tratamento",
      "B": "suspender a medicação por 7 dias a partir da vacinação",
      "C": "vacinar a criança com as orientações habituais",
      "D": "vacinar a criança com a dose dobrada da vacina",
      "E": "vacinar a criança, advertindo quanto à possibilidade de reações vacinais mais intensas."
    },
    "answer": "C",
    "area": "Pediatria",
    "assunto": "Puericultura",
    "topico": "Imunizações/Vacinação",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-045",
    "number": 45,
    "stem": "Dentre as situações a seguir, aquela em que o recém-nascido tem dois critérios para icterícia patológica é:\n(A) RN a termo, icterícia desde 37 horas de vida, bilirrubina total = 4 mg/dl, bilirrubina indireta = 3,1 mg/dl;\n(B) RN prematuro, 6º dia de vida, bilirrubina total = 3 mg/dl, bilirrubina indireta = 2,2 mg/dl;\n(C) RN a termo, icterícia nas primeiras 12 horas de vida, bilirrubina total = 2 mg/dl, bilirrubina indireta = 0,8 mg/dl;\n(D) RN prematuro, 39 horas de vida, bilirrubina total = 8 mg/dl, aumento de bilirrubina em seis horas = 0,1 mg/dl/hora;\n(E) RN prematuro, grupo sanguíneo/RH: RN = O+ e mãe =A+, ictérico no 12º dia de vida.",
    "options": {
      "A": "RN a termo, icterícia desde 37 horas de vida, bilirrubina total = 4 mg/dl, bilirrubina indireta = 3,1 mg/dl",
      "B": "RN prematuro, 6º dia de vida, bilirrubina total = 3 mg/dl, bilirrubina indireta = 2,2 mg/dl",
      "C": "RN a termo, icterícia nas primeiras 12 horas de vida, bilirrubina total = 2 mg/dl, bilirrubina indireta = 0,8 mg/dl",
      "D": "RN prematuro, 39 horas de vida, bilirrubina total = 8 mg/dl, aumento de bilirrubina em seis horas = 0,1 mg/dl/hora",
      "E": "RN prematuro, grupo sanguíneo/RH: RN = O+ e mãe =A+, ictérico no 12º dia de vida."
    },
    "answer": "C",
    "area": "Pediatria",
    "assunto": "Neonatologia",
    "topico": "Icterícia nenonatal e distúrbios hematológicos no RN",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-046",
    "number": 46,
    "stem": "Segundo os critérios de ROMA IV para lactentes, escolares e adolescentes, na síndrome do intestino irritável:\n(A) a criança tem diarreia associada a perda ponderal nos últimos 2 meses;\n(B) a dor abdominal é aliviada após resolução da constipação;\n(C) a dor abdominal é acompanhada de alteração na frequência das evacuações;\n(D) a criança tem evacuação Bristol 6 na primeira evacuação do dia, seguida por Bristol 1 nas demais evacuações;\n(E) os sintomas acontecem por pelo menos 1 mês antes do diagnóstico.",
    "options": {
      "A": "a criança tem diarreia associada a perda ponderal nos últimos 2 meses",
      "B": "a dor abdominal é aliviada após resolução da constipação",
      "C": "a dor abdominal é acompanhada de alteração na frequência das evacuações",
      "D": "a criança tem evacuação Bristol 6 na primeira evacuação do dia, seguida por Bristol 1 nas demais evacuações",
      "E": "os sintomas acontecem por pelo menos 1 mês antes do diagnóstico."
    },
    "answer": "C",
    "area": "Pediatria",
    "assunto": "Gastrologia Pediátrica",
    "topico": "Diarreia Aguda",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-047",
    "number": 47,
    "stem": "M-CHAT-R é um teste utilizado no transtorno do espectro autista para:\n(A) diagnóstico da síndrome de Asperger;\n(B) triagem dos sinais precoces;\n(C) acompanhamento do neurodesenvolvimento;\n(D) avaliação de TEA entre 9 e 15 meses de idade;\n(E) estadiamento do grau de autismo.",
    "options": {
      "A": "diagnóstico da síndrome de Asperger",
      "B": "triagem dos sinais precoces",
      "C": "acompanhamento do neurodesenvolvimento",
      "D": "avaliação de TEA entre 9 e 15 meses de idade",
      "E": "estadiamento do grau de autismo."
    },
    "answer": "B",
    "area": "Pediatria",
    "assunto": "Neuropediatria",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-048",
    "number": 48,
    "stem": "Uma primípara comparece à consulta de puericultura com seu filho de 2 meses. Durante a consulta, o pediatra percebe que ela está prestes a abandonar o aleitamento materno exclusivo e conduz a conversa de forma a mantê-lo.\nNessa conversa é importante ser empático, evitando:\n(A) fazer perguntas abertas que permitam à mãe expressar argumentos contra a manutenção da amamentação;\n(B) recorrer à comunicação não verbal, uma vez que esta pode induzir a erros de interpretação, tornar-se inapropriada ou gerar problemas éticos;\n(C) aceitar as opiniões da mãe durante a conversa, a fim de demonstrar, de forma clara e incisiva, que a posição expressa nessas opiniões está equivocada;\n(D) usar palavras que possam ser interpretadas como julgamento, exceto quando possam efetivamente levar ao desmame;\n(E) subestimar os sentimentos da mãe, a fim de demonstrar, durante a conversa, que eles podem ser compreendidos e valorizados.",
    "options": {
      "A": "fazer perguntas abertas que permitam à mãe expressar argumentos contra a manutenção da amamentação",
      "B": "recorrer à comunicação não verbal, uma vez que esta pode induzir a erros de interpretação, tornar-se inapropriada ou gerar problemas éticos",
      "C": "aceitar as opiniões da mãe durante a conversa, a fim de demonstrar, de forma clara e incisiva, que a posição expressa nessas opiniões está equivocada",
      "D": "usar palavras que possam ser interpretadas como julgamento, exceto quando possam efetivamente levar ao desmame",
      "E": "subestimar os sentimentos da mãe, a fim de demonstrar, durante a conversa, que eles podem ser compreendidos e valorizados."
    },
    "answer": "E",
    "area": "Pediatria",
    "assunto": "Puericultura",
    "topico": "Puericultura Geral",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-057",
    "number": 57,
    "stem": "A síndrome urêmica hemolítica típica (SHU) é uma doença do grupo das microangiopatias trombóticas. São distúrbios caracterizados por anemia hemolítica microangiopática não imune, trombocitopenia e insuficiência multissistêmica. A SHU está associada a infecções intestinais por bactérias produtoras da toxina Shiga, em especial a Escherichia coli enterohemorrágica invasiva (STEC - Shiga-toxin– producing strains of E coli). Carne mal-cozida, especialmente hambúrguer, leite e suco não pasteurizados, além de frutas e vegetais crus, podem estar contaminados por essas bactérias.\nA doença geralmente tem início abrupto com quadro de diarreia, muitas vezes com sangue e dor abdominal. Em adultos, geralmente é autolimitada a 5-10 dias. Porém, em crianças, observa-se maior associação à SHU.\nCom relação a essa doença em crianças, é correto afirmar que:",
    "options": {
      "A": "o antibiótico de escolha é o ciprofloxacino;",
      "B": "a terapia antibiótica pode aumentar o risco de SHU e a plasmaférese pode auxiliar pacientes com doença por e. coli enterohemorrágica invasiva produtora da toxina SHIGA;",
      "C": "rifaximina associada a fluorquinolona deve ser administrada imediatamente em casos de diarreia hemorrágica;",
      "D": "vancomicina 125 mg, por via oral, quatro vezes ao dia, associada a fidaxomicina 200 mg, duas vezes ao dia durante 10 dias, é o tratamento indicando;",
      "E": "sulfametoxazol + trimetoprima 800/160 mg a cada 6h por 28 dias é o tratamento de escolha."
    },
    "answer": "B",
    "area": "Infectologia",
    "assunto": "Infecções bacterianas",
    "topico": "Infecção de pele e partes moles (Piodermites)",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-058",
    "number": 58,
    "stem": "Coqueluche é uma infecção aguda do trato respiratório causada pela bactéria Bordetella pertussis. A palavra coqueluche significa “tosse violenta”, expressão que descreve apropriadamente a característica mais consistente e proeminente da doença. O nome chinês para coqueluche é “tosse de 100 dias”, termo que descreve o curso clínico da doença com precisão. A identificação de B. pertussis foi relatada pela primeira vez por Bordet e Gengou em 1906.\nA classe de antibióticos mais adequada para tratamento dessa doença é:",
    "options": {
      "A": "fosfomicina;",
      "B": "quinolona;",
      "C": "tetraciclina;",
      "D": "beta-lactâmico;",
      "E": "macrolídeos."
    },
    "answer": "E",
    "area": "Infectologia",
    "assunto": "Infecções bacterianas",
    "topico": "Difteria",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-059",
    "number": 59,
    "stem": "Um lactente de 9 meses, com fácies sindrômica, assintomático, apresenta ausculta cardíaca com ritmo regular, bulhas normofonéticas com desdobramento variável da segunda bulha, sopro sistólico 2+/6+ mais audível em borda esternal esquerda baixa, sem irradiação, que diminui com a posição sentada. Os pulsos femorais são palpáveis. \nNesse caso, o médico deve:",
    "options": {
      "A": "internar a criança para realização de exames;",
      "B": "encaminhar a criança para avaliação do cardiopediatra;",
      "C": "iniciar medicação cardiológica (furosemida e captopril);",
      "D": " solicitar teste de oximetria de pulso;",
      "E": "considerar o achado como funcional, sem necessidade de encaminhamento."
    },
    "answer": "E",
    "area": "Pediatria",
    "assunto": "Cardiologia Pediátrica",
    "topico": "Cardiopediatria e Cardiopatias congênitas",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-060",
    "number": 60,
    "stem": "Um escolar de 10 anos apresenta queixa de cansaço, dores nas pernas que o acordam durante a noite e emagrecimento de 2 kg no último mês. Apresenta as seguintes alterações ao exame físico: palidez cutâneo-mucosa 3+/4+, sopro sistólico 2+/6+ em bordo esternal esquerdo, taquicardia (FC = 120 bpm), fígado a 2,5 cm do RCD, ponta de baço palpável, dor à palpação do terço proximal da tíbia bilateralmente e petéquias esparsas em membros.\nO quadro clínico é sugestivo de:",
    "options": {
      "A": "anemia falciforme;",
      "B": "leucemia;",
      "C": "zika vírus;",
      "D": "endocardite infecciosa;",
      "E": "toxoplasmose."
    },
    "answer": "B",
    "area": "Pediatria",
    "assunto": "Hematologia Pediátrica",
    "topico": "Anemia ferropriva na infância",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-061",
    "number": 61,
    "stem": "Uma paciente de 24 anos, saudável, é usuária de dispositivo intrauterino de cobre. Refere vida sexual ativa com uso de preservativos e última menstruação há 10 dias. Há 2 horas, iniciou-se uma dor de instalação aguda, de padrão constante, em fossa ilíaca direita, sem irradiação, associada a náuseas e vômitos. Nega sangramento vaginal, febre, dor lombar, mudança de hábito intestinal ou urinário. A ultrassonografia transvaginal evidenciou aumento do ovário direito, comprometimento do fluxo sanguíneo em região anexial do mesmo lado e líquido livre em fundo de saco.\nA hipótese mais provável é:",
    "options": {
      "A": "gestação ectópica à direita;",
      "B": "abscesso ovariano à direita;",
      "C": "torção de ovário e tuba uterina à direita;",
      "D": "apendicite;",
      "E": "pielonefrite à direita."
    },
    "answer": "C",
    "area": "Ginecologia",
    "assunto": "Ginecologia geral",
    "topico": "Abdome agudo em ginecologia",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-062",
    "number": 62,
    "stem": "Uma paciente de 18 anos chega à emergência do hospital referindo ter sido vítima de violência sexual há 2 horas em uma festa. Refere que, no ato, houve penetração. Ela desconhece o agressor, o qual não usou preservativo.\nA abordagem inicial deve incluir:",
    "options": {
      "A": "atendimento inicial exclusivo por médico;",
      "B": "encaminhamento da paciente primeiramente ao instituto médico legal;",
      "C": "encaminhamento da paciente para realizar boletim de ocorrência antes do atendimento médico;",
      "D": "início de profilaxia para as doenças sexualmente transmissíveis e prevenção de gravidez em até 5 dias;",
      "E": "avaliação do estado geral de saúde, orientação e proteção contra doenças de transmissão sexual, prevenção de gravidez e coleta de materiais biológicos ou outros indícios materiais que permitam a identificação do agressor."
    },
    "answer": "E",
    "area": "Ginecologia",
    "assunto": "Sexualidade",
    "topico": "Tratamento",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-063",
    "number": 63,
    "stem": "Uma paciente de 23 anos tem queixa de irregularidade menstrual de longa data. Refere que, desde a primeira menstruação, tem intervalo de 50 a 60 dias entre os ciclos e períodos de amenorreia. No último ano, estava em final de faculdade e ganhou muito peso em função de estresse e sedentarismo. Ao exame, apresenta bom estado geral, IMC 31 kg/m2, presença de acne em face e dorso e escurecimento de região de dobras.\nFrente a esse cenário, a principal hipótese é:",
    "options": {
      "A": "síndrome dos ovários policísticos;",
      "B": "sobrepeso com aumento de gordura visceral;",
      "C": "deficiência enzimática da suprarrenal da 21-hidroxilase;",
      "D": "síndrome de Cushing;",
      "E": "hipotireoidismo."
    },
    "answer": "A",
    "area": "Ginecologia",
    "assunto": "Ginecologia endócrina",
    "topico": "Síndrome dos ovários policísticos",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-064",
    "number": 64,
    "stem": "Uma paciente de 38 anos teve diagnóstico de câncer de mama há 18 meses, com realização de quimioterapia neoadjuvante e mastectomia à direita. Não menstrua há 12 meses. Há 6 meses queixa-se de calores e suores todas as noites, com prejuízo importante de sua qualidade de vida. Recentemente notou piora da lubrificação vaginal.\nAnalisando o caso acima, o diagnóstico e a conduta apropriada são, respectivamente:",
    "options": {
      "A": "menopausa precoce; início de terapia hormonal com estrogênio e progesterona via oral e uso de lubrificantes vaginais;",
      "B": "menopausa precoce; início de escitalopram e hidratantes vaginais;",
      "C": "menopausa precoce; início de estriol vaginal e laser vaginal;",
      "D": "cessação temporária da menstruação; início de desvenlafaxina e lubrificantes vaginais;",
      "E": "transição menopausal; início de estriol transdérmico e fisioterapia pélvica."
    },
    "answer": "B",
    "area": "Ginecologia",
    "assunto": "Mastologia",
    "topico": "Câncer de mama",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-065",
    "number": 65,
    "stem": "Uma criança do sexo feminino, de 2 anos de idade, chega encaminhada pelo seu pediatra. A mãe relata corrimento vaginal ora sanguinolento, ora aquoso e uma estrutura semelhante a \"cachos de uva\" de aspecto gelatinoso na entrada da vagina.\nA principal hipótese é:\n(A) má higiene;\n(B) sarcoma botrioide;\n(C) corpo estranho;\n(D) contaminação com gel hormonal transdérmico da mãe;\n(E) estímulo hormonal remanescente do intraútero.",
    "options": {
      "A": "má higiene;",
      "B": "sarcoma botrioide;",
      "C": "corpo estranho;",
      "D": "contaminação com gel hormonal transdérmico da mãe;",
      "E": "estímulo hormonal remanescente do intraútero."
    },
    "answer": "B",
    "area": "Ginecologia",
    "assunto": "Oncologia ginecológica",
    "topico": "Doenças de vulva e vagina",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-066",
    "number": 66,
    "stem": "Paciente de 32 anos foi à consulta ginecológica de rotina para realização de colpocitologia oncótica. O exame evidenciou agrupamento de células escamosas com núcleos aumentados, hipercrômicos e irregulares, com alta relação núcleo-citoplasmática sugestiva de lesão intraepitelial de alto grau. Como a amostra foi coletada em meio líquido, foi solicitado teste de HPV, que veio positivo para o subtipo 16.\nFrente a essas informações, é correto afirmar que:\n(A) se trata de exame normal, com seguimento em 3 anos;\n(B) pela associação com HPV-16, a lesão é considerada de baixo grau;\n(C) se trata de uma lesão de alto grau com infecção por HPV de alto risco oncogênico, sendo indicada colposcopia;\n(D) por se tratar de uma infecção por HPV de baixo risco oncogênico, está indicado seguimento semestral;\n(E) se trata de uma infecção por HPV de alto risco oncogênico, sendo indicada a realização imediata da exérese da zona de transformação (EZT ou LEEP), sem a necessidade de colposcopia.",
    "options": {
      "A": "se trata de exame normal, com seguimento em 3 anos;",
      "B": "pela associação com HPV-16, a lesão é considerada de baixo grau;",
      "C": "se trata de uma lesão de alto grau com infecção por HPV de alto risco oncogênico, sendo indicada colposcopia;",
      "D": "por se tratar de uma infecção por HPV de baixo risco oncogênico, está indicado seguimento semestral;",
      "E": "se trata de uma infecção por HPV de alto risco oncogênico, sendo indicada a realização imediata da exérese da zona de transformação (EZT ou LEEP), sem a necessidade de colposcopia."
    },
    "answer": "C",
    "area": "Ginecologia",
    "assunto": "Oncologia ginecológica",
    "topico": "Rastreamento do câncer de colo do útero",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-067",
    "number": 67,
    "stem": "Uma mulher de 63 anos, portadora de carcinoma lobular invasivo de mama direita de 2,0 cm, com axila clinicamente livre, é submetida a quadrantectomia com biópsia de linfonodo sentinela. Durante o exame de congelação intraoperatória, o patologista encontra a presença de células carcinomatosas nos linfonodos sentinelas biopsiados. É indicado o esvaziamento axilar. Para tanto, é importante definir quais são os 3 níveis dos linfonodos axilares.\nA estrutura anatômica que define esses níveis é:\n(A) a artéria axilar;\n(B) o músculo peitoral maior;\n(C) o músculo peitoral menor;\n(D) a artéria mamária interna;\n(E) o nervo intercostobraquial.",
    "options": {
      "A": "a artéria axilar;",
      "B": "o músculo peitoral maior;",
      "C": "o músculo peitoral menor;",
      "D": "a artéria mamária interna;",
      "E": "o nervo intercostobraquial."
    },
    "answer": "C",
    "area": "Ginecologia",
    "assunto": "Oncologia ginecológica",
    "topico": "Tumores anexiais e câncer de ovário",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-068",
    "number": 68,
    "stem": "Uma menina de 6 anos é levada pela mãe ao ginecologista por ter iniciado desenvolvimento mamário há 4 meses. Ao exame físico, apresenta mamas em estágio M2 de Tanner e genitália em estágio P1 de Tanner. De acordo com o gráfico de velocidade de crescimento, a paciente manteve um padrão de 4 cm/ano no último ano. Realizada uma radiografia de mão e de punhos pelo método de Greulich-Pyle, identifica-se que a idade óssea da criança é estimada em 6 anos e 2 meses. A dosagem hormonal de LH é 1,2 UI/L.\nConsiderando as informações acima, o diagnóstico mais provável é:\n(A) telarca precoce isolada;\n(B) pubarca precoce isolada;\n(C) menarca precoce isolada;\n(D) puberdade precoce central;\n(E) puberdade precoce periférica.",
    "options": {
      "A": "telarca precoce isolada;",
      "B": "pubarca precoce isolada;",
      "C": "menarca precoce isolada;",
      "D": "puberdade precoce central;",
      "E": "puberdade precoce periférica."
    },
    "answer": "A",
    "area": "Ginecologia",
    "assunto": "Ginecologia endócrina",
    "topico": "Sangramento uterino anormal",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-069",
    "number": 69,
    "stem": "Uma mulher de 23 anos, sexualmente ativa, utilizando contracepção com pílula hormonal combinada, refere surgimento de lesões ulceradas, dolorosas em face interna de grande lábio esquerdo, há 3 dias. Precedendo o surgimento das lesões, refere que a região acometida apresentou um aumento de sensibilidade. Além disso, relata ter apresentado quadro de faringite há 1 semana. Ao exame físico, identifica-se a vulva trófica, sem distopias aparentes, apresentando 5 lesões ulceradas, com menos de 0,5 cm cada, coalescendo, dolorosas ao toque. Há presença de micropolilinfadenopatia inguinal bilateral, indolor.\nConsiderando a principal hipótese diagnóstica, a opção adequada de tratamento para a paciente é:\n(A) aciclovir 400 mg, três vezes ao dia, por 7 a 14 dias;\n(B) ceftriaxona 1g, IV ou IM, uma vez ao dia, por 8 a 10 dias;\n(C) doxiciclina 100 mg, VO, duas vezes ao dia, por 10 a 15 dias;\n(D) prednisona, 20 mg, VO, uma vez ao dia, até remissão da úlcera;\n(E) penicilina G benzatina, 2,4 milhões UI, IM, dose única (1,2 milhão UI em cada glúteo).",
    "options": {
      "A": "aciclovir 400 mg, três vezes ao dia, por 7 a 14 dias;",
      "B": "ceftriaxona 1g, IV ou IM, uma vez ao dia, por 8 a 10 dias;",
      "C": "doxiciclina 100 mg, VO, duas vezes ao dia, por 10 a 15 dias;",
      "D": "prednisona, 20 mg, VO, uma vez ao dia, até remissão da úlcera;",
      "E": "penicilina G benzária, 2,4 milhões UI, IM, dose única (1,2 milhão UI em cada glúteo)."
    },
    "answer": "A",
    "area": "Ginecologia",
    "assunto": "Infecções em ginecologia",
    "topico": "Úlceras genitais",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-070",
    "number": 70,
    "stem": "Uma mulher de 63 anos, portadora de diabetes mellitus e hipertensão arterial sistêmica controlada, encontra-se em menopausa há 10 anos. Comparece ao ginecologista com queixas de sangramento vaginal há 3 meses. O exame físico não apresenta alterações aparentes ou sinais de sangramento ativo no momento. É realizada uma ultrassonografia transvaginal, que evidencia endométrio com 3 mm de espessura, com imagem ecogênica focal que ocupa a interface entre os folhetos endometriais e mede 5 mm no maior eixo.\nA causa mais provável do sangramento nesse caso é:\n(A) adenomiose;\n(B) pólipo endometrial;\n(C) miomatose uterina;\n(D) hiperplasia endometrial;\n(E) adenocarcinoma do endométrio.",
    "options": {
      "A": "adenomiose;",
      "B": "pólipo endometrial;",
      "C": "miomatose uterina;",
      "D": "hiperplasia endometrial;",
      "E": "adenocarcinoma do endométrio."
    },
    "answer": "B",
    "area": "Ginecologia",
    "assunto": "Ginecologia geral",
    "topico": "Pólipos uterinos",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-071",
    "number": 71,
    "stem": "Uma mulher de 25 anos, sexualmente ativa, sem atraso menstrual, comparece ao ginecologista com uma ultrassonografia transvaginal de rotina que apresentou nódulo de aspecto misto, com áreas hiperecogênicas difusas e sombra acústica posterior no ovário direito medindo 7,0 cm. O ovário esquerdo e o útero não apresentaram alterações à ultrassonografia. Ao toque vaginal, identificou-se a presença de massa móvel, indolor, medindo em torno de 7,0 cm, palpável em região anexial direita.\nConsiderando a principal hipótese diagnóstica do caso, é correto afirmar que:\n(A) esse tipo de tumor ovariano é bilateral em 10% dos casos;\n(B) usualmente o marcador tumoral CA125 é elevado nesses casos;\n(C) a chance de malignidade desse tipo de tumor é usualmente alta;\n(D) o principal subtipo histológico desses tumores é o cistoadenocarcinoma seroso;\n(E) o tratamento de eleição para esse tipo de tumor é a histerectomia com ooforectomia bilateral.",
    "options": {
      "A": "esse tipo de tumor ovariano é bilateral em 10% dos casos;",
      "B": "usualmente o marcador tumoral CA125 é elevado nesses casos;",
      "C": "a chance de malignidade desse tipo de tumor é usualmente alta;",
      "D": "o principal subtipo histológico desses tumores é o cistoadenocarcinoma seroso;",
      "E": "o tratamento de eleição para esse tipo de tumor é a histerectomia com ooforectomia bilateral."
    },
    "answer": "A",
    "area": "Ginecologia",
    "assunto": "Oncologia ginecológica",
    "topico": "Tumores anexiais e câncer de ovário",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-072",
    "number": 72,
    "stem": "Uma mulher de 33 anos comparece ao médico com queixa de leucorreia há 2 semanas, com odor desagradável, que piora após a relação sexual. Ao exame especular, verifica-se conteúdo vaginal aumentado, com coloração branco-acinzentada e algo bolhoso. O colo uterino apresenta mácula rubra de 2,0 cm de diâmetro ao redor do orifício externo, e o muco cervical está com aspecto transparente. A fita de pH vaginal registra resultado de 5,2. O teste do KOH10% exacerbou o odor da leucorreia. Ao toque vaginal, o colo móvel apresenta-se indolor. Realizada a bacterioscopia, visualizaram-se células epiteliais recobertas por cocobacilos Gram variáveis.\nConsiderando a principal hipótese diagnóstica, o melhor tratamento para a paciente é:\n(A) fluconazol, 1 comprimido de 150 mg em dose única;\n(B) duchas vaginais com bicarbonato de sódio por 10 dias;\n(C) fenticonazol, creme vaginal, 0,02 mg/g, uma vez ao dia, durante 7 dias;\n(D) metronidazol 500 mg, por via oral, duas vezes ao dia, durante 7 dias;\n(E) creme vaginal combinando clindamicina 2% e hidrocortisona 10%, por 14 dias.",
    "options": {
      "A": "fluconazol, 1 comprimido de 150 mg em dose única;",
      "B": "duchas vaginais com bicarbonato de sódio por 10 dias;",
      "C": "fenticonazol, creme vaginal, 0,02 mg/g, uma vez ao dia, durante 7 dias;",
      "D": "metronidazol 500 mg, por via oral, duas vezes ao dia, durante 7 dias;",
      "E": "creme vaginal combinando clindamicina 2% e hidrocortisona 10%, por 14 dias."
    },
    "answer": "D",
    "area": "Ginecologia",
    "assunto": "Infecções em ginecologia",
    "topico": "Vulvovaginites",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-073",
    "number": 73,
    "stem": "Paciente, após gestação e parto complicados, está em acompanhamento com endocrinologista com diagnóstico de síndrome de Sheehan.\nA complicação obstétrica que mais provavelmente ocorreu nesse caso foi:\n(A) diabetes gestacional em uso de insulina;\n(B) descolamento prematuro da placenta;\n(C) rotura prematura de membranas ovulares;\n(D) gestação gemelar monocoriônica;\n(E) restrição de crescimento intrauterino.",
    "options": {
      "A": "diabetes gestacional em uso de insulina",
      "B": "descolamento prematuro da placenta",
      "C": "rotura prematura de membranas ovulares",
      "D": "gestação gemelar monocoriônica",
      "E": "restrição de crescimento intrauterino"
    },
    "answer": "B",
    "area": "Obstetrícia",
    "assunto": "Intercorrências obstétricas /obstetrícia patológica",
    "topico": "Sangramento segunda metade da gestação",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-074",
    "number": 74,
    "stem": "A pré-eclâmpsia complicada com síndrome HELLP é caracterizada por:\n(A) trombocitopenia e convulsões maternas;\n(B) disfunção hepática e elevação da glicemia;\n(C) hemólise, disfunção hepática e trombocitopenia;\n(D) convulsões maternas, hemólise e hiperglicemia;\n(E) diminuição dos reflexos profundos e hemólise.",
    "options": {
      "A": "trombocitopenia e convulsões maternas",
      "B": "disfunção hepática e elevação da glicemia",
      "C": "hemólise, disfunção hepática e trombocitopenia",
      "D": "convulsões maternas, hemólise e hiperglicemia",
      "E": "diminuição dos reflexos profundos e hemólise"
    },
    "answer": "C",
    "area": "Obstetrícia",
    "assunto": "Intercorrências obstétricas /obstetrícia patológica",
    "topico": "Sangramento segunda metade da gestação",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-075",
    "number": 75,
    "stem": "Uma gestante com 28 semanas tem o diagnóstico de infecção por parvovírus B19.\nA melhor maneira de avaliar a principal complicação fetal nesse caso é:\n(A) realização do doppler da artéria cerebral média;\n(B) avaliação ultrassonográfica da movimentação fetal;\n(C) pesquisa de células fetais livres no sangue materno;\n(D) medida menor do fundo uterino ao exame clínico;\n(E) realização do teste de Coombs direto no sangue materno.",
    "options": {
      "A": "realização do doppler da artéria cerebral média",
      "B": "avaliação ultrassonográfica da movimentação fetal",
      "C": "pesquisa de células fetais livres no sangue materno",
      "D": "medida menor do fundo uterino ao exame clínico",
      "E": "realização do teste de Coombs direto no sangue materno"
    },
    "answer": "A",
    "area": "Obstetrícia",
    "assunto": "Doenças associadas à gestação",
    "topico": "Doenças infecciosas na gestação – HIV, sífilis, hepatites, herpes",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-078",
    "number": 78,
    "stem": "Uma mulher de 25 anos chega ao ambulatório com um exame de farmácia demonstrando gravidez. Ainda não realizou ultrassonografia e, pela data da última menstruação, estaria com aproximadamente 8 semanas de gestação.\nAo toque, nota-se um amolecimento acentuado no istmo, que configuraria o sinal de:\n(A) Hegar;\n(B) Piskacek;\n(C) Osiander;\n(D) Nobile-Budin;\n(E) Puzos.",
    "options": {
      "A": "Hegar",
      "B": "Piskacek",
      "C": "Osiander",
      "D": "Nobile-Budin",
      "E": "Puzos"
    },
    "answer": "A",
    "area": "Obstetrícia",
    "assunto": "Obstetrícia fisiológica",
    "topico": "Modificações fisiológicas da gestação",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-079",
    "number": 79,
    "stem": "Uma gestante de 38 anos, secundigesta e cardiopata, chega à emergência referindo cólicas intensas, sangramento vaginal em grande quantidade e sangue vivo. A idade gestacional, estabelecida pela ultrassonografia transvaginal realizada com 6 semanas, é de 9 semanas e 3 dias. Ao exame, o útero encontra-se aumentado de volume, amolecido, com colo entreaberto e saída de material ovular identificada no exame especular. A ultrassonografia mostra a presença de restos ovulares em grande quantidade.\nDiante desse quadro, a conduta deve ser:\n(A) esvaziamento uterino por aspiração a vácuo ou curetagem;\n(B) ocitocina venosa, 20 UI em 500 ml de soro fisiológico;\n(C) expectante, monitorando a pressão arterial e sangramento;\n(D) misoprostol retal na dose de 800 mcg em dose única;\n(E) realização de nova ultrassonografia transvaginal em 12 horas.",
    "options": {
      "A": "esvaziamento uterino por aspiração a vácuo ou curetagem",
      "B": "ocitocina venosa, 20 UI em 500 ml de soro fisiológico",
      "C": "expectante, monitorando a pressão arterial e sangramento",
      "D": "misoprostol retal na dose de 800 mcg em dose única",
      "E": "realização de nova ultrassonografia transvaginal em 12 horas"
    },
    "answer": "A",
    "area": "Obstetrícia",
    "assunto": "Intercorrências obstétricas /obstetrícia patológica",
    "topico": "Sangramento primeira metade",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  },
  {
    "id": "enare-2024-080",
    "number": 80,
    "stem": "Uma gestante de 20 semanas, moradora de área endêmica, chegou à admissão da maternidade com sinais e sintomas sugestivos de dengue.\nApós o exame clínico-obstétrico e laboratorial, a equipe de plantão resolveu internar e tratar a paciente, pois identificou corretamente o seguinte sinal de alarme:\n(A) vômitos esporádicos;\n(B) dor abdominal moderada;\n(C) hipotensão postural e/ou lipotimia;\n(D) diminuição progressiva do hematócrito;\n(E) esplenomegalia 1 cm abaixo do rebordo costal.",
    "options": {
      "A": "vômitos esporádicos",
      "B": "dor abdominal moderada",
      "C": "hipotensão postural e/ou lipotimia",
      "D": "diminuição progressiva do hematócrito",
      "E": "esplenomegalia 1 cm abaixo do rebordo costal"
    },
    "answer": "C",
    "area": "Obstetrícia",
    "assunto": "Doenças associadas à gestação",
    "topico": "Doenças infecciosas na gestação – HIV, sífilis, hepatites, herpes",
    "annulled": false,
    "images": [],
    "source": "enare-2024",
    "examId": "enare-2024",
    "examName": "ENARE-2024"
  }
]);
