// Catálogo curricular do OSCE. Não contém casos clínicos ou gabaritos.
// Cada item é um subtema; esta estrutura é compartilhada pela API e pelo seed.
const groups = [
  ['Atenção Primária à Saúde', [
    ['A', ['Saúde e doença (prevenção primária, secundária, terceária e quarternária e modelos do processo saúde e doença) + Sistema de Saúde Suplementar - Agência Nacional de Saúde Suplementar.','Ética médica (Princípios e diretrizes do código de ética médica e sua aplicação).','Sistema Único de Saúde - SUS + Leis Orgânicas de Saúde (diretrizes do SUS, lei 8080 e lei 8142).','Dinâmica de transmissão e distribuição de doenças e Vigilância em Saúde com ênfase em Vigilância epidemiológica (Doenças de notificação compulsoria no Brasil, SINAN e Ficha de Notificação de agravo - preenchimento e fluxo de informação, Vigilâcia Epidemiológica - conceito, importancia e atuação).','Transição epidemiológica, demográfica e nutricional.','Aspectos biológicos e fisiologia do envelhecimento (diferença entre senilidade e senescência e suas implicações clínicas, envelhecimento saudável)','Avaliacao global do Idoso (exame físico do idoso, MEEM, Escala de Depressão Geriatrica, e outras ferramentas de avaliação).','Instabilidade postural e quedas (critérios diagnósticos, manifestações clínicas e os métodos de avaliação para a instabilidade postural em idosos e fatores de risco para quedas.).','Violência e maus-tratos contra os idosos.','Sindrome Gripal (conceito da síndrome gripal, características clínicas e diagnosticos diferenciais e plano terapeutico.).','Rastreamento de doenças na APS I (foco em neoplasias: colo de útero, mama, próstata, colorretal).','Rastreamento de doenças na APS II (foco em HAS, DM, Dislipidemia, Obesidade).']],
    ['B', ['Atenção Primária à Saúde e Estratégia de Saúde da Família (Promoção à saúde, Atributos da APS, composição e atribuições da equipe de SF.).','Medicina de Família e Comunidade e Programa Mais Médicos.','Análise de métodos diagnósticos e Estudos epidemiológicos (Sensibilidade, especificidade, valor preditivo positivo e negativo, prevalência e incidência.).','Medicina legal (principais documentos médicos).','Medicina baseada em evidências, revisão sistemática e meta-análise.','Visitas Domiciliares e Atenção Domiciliar na ESF.','Complexidade e Integralidade na APS e DCNT.','DM e HAS Centrada na Pessoa.','Violência e maus-tratos contra a criança e a adolescente.','Vacinação (indicações, contra-indicações, efeitos adversos, faixa etária).','Violência Sexual e Autoprovocada + Doencas de notificação compulsória.','Saúde do Trabalhador + CAT.']]
  ]],
  ['Cirurgia', [
    ['A', ['Abdome agudo inflamatório e suas complicações (apendicite, colicistite, diverticulite)','Hérnias de Parede Abdominal','Complicações e cuidados pós-operatórias; Infecção em cirurgia - Hematoma - Seroma - Deiscência - Evisceração.','Resposta endócrino metabólica ao trauma','Cuidados pré-operatórios; Risco cirúrgico (ASA - Goldman)','Afecções hepáticas: diagnósgtico/tratamento/complicações (Hipertensão portal; nódulos e abcessos hepáticos;)','Afecções da árvore biliar: colecistolitíase, coledocolitíase, íleo biliar, colangiocarcinoma','Afecções do pâncreas (Pancreatite aguda e crônica, pseudocisto, neoplasias císticas, adenocarcinoma): diagnóstico/tratamento/complicações','Câncer de cólon e reto (Diagnóstico clinico, laboratorial, radiologico e Condução clínica.','Condutas intervencionistas em derrame pleural Toracocentese','Tipos de fios, suturas e feridas.','Doenças orificiais: Doença hemorroidária, fissura anal, fístula anal, abscesso anorretal']],
    ['B', ['ATLS- Aspectos históricos, exame primário e secundário, fase de cada um dos exames, aspectos intervencionistas no exameprimário e secundário','Cicatrização','Via áerea cirurgica','Trauma torácico (Pneumotórax aberto, fechado e hipertensivo, hemotórax, contusão pulmonar, tórax instável e tamponamento cardíaco)','Trauma abdominal e pélvico','Acesso venoso central','Queimaduras / síndrome compartimental','DAOP + Obstrução arterial aguda; Aneurisma de aorta','Insuficiência venosa crônica; Trombose Venosa Profunda - TVP','Noções de anestesia periférica','Urgências urológicas: Torção testicular, priapismo, urolitíase e orquiedpidimite','Abdome agudo em pediatria: intussuscepção, vólvulo, má rotação intestinal']]
  ]],
  ['Clínica Médica', [
    ['A', ['Asma e DPOC (Exame físico e exames complementares, incluindo espirometria, Tratamento da DPOC pelo ABE do GOLD, tratamento da exacerbação)','Diabetes mellitus - Classificação, diagnóstico, tratamento e complicações','Dengue, Zika, Chikungunya e Febre Amarela','Doenças do Pericárdio, Miocardites e Endocardites','HIV e Criptococosse','Cirrose e complicações (PBE, Asciste, Encefalopatia hepática, Síndrome hepatorrenal)','Doenças Eritematodescamativas (Psoríase, Dermatite Atópica)','Injúria Renal Aguda e Doença Renal Crônica','Doenças Tubulointersticiais e Glomerulares','Infecção de Trato Urinário, Nefrolitíase','Síndrome metabólica e dislipidemias','Doenças da hipófise e da tireóide - Rastreio de nódulos tireóidianos']],
    ['B', ['Insuficiencia cardíaca e valvopatias','Hipertensão arterial sistêmica, Emergências Hipertensivas, Encefalopatia hipertensiva, Crise hipertensiva, Conceitos fundamentais e condução clínica','Cefaleia na urgência / Principais cefaleias primárias: Cefaleia tensional, enxaqueca e cefaleias em salva','Tuberculose e Hanseníase (epidemiologia, fatores de risco, características do bacilo de koch, mecanismos de infecção e latência, tuberculose extrapulmonar, prevenção e controle, propedêutica clínica, diagnóstico e tratamento).','DRGE e Dispepsia (Dispepsia funcional, gastrites - incluindo quadro clínico, fisiopatologia, diagnóstico e tratamento)','Doenças inflamatórias intestinais (doença de crohn, retocolite ulcerativa)','Hemoragias digestivas (alta, média e baixa)','TVP e Tromboembolismo pulmonar (fatores de risco, exames complementares, tratamento e profilaxia)','Anemias (carenciais, hemolíticas e de doença crônica)','Neoplasias Hematológicas (Linfoma e Leucemia - Avaliação inicial e triagem laboratorial)','Pneumonias Bacterianas, virais e atípicas.','Poliartrites: Artrite Reumatóiide e Osteoartrite']]
  ]],
  ['Ginecologia e Obstetrícia', [
    ['A', ['Assistência pré-natal','O parto: assistência clínica, mecanismos, períodos e manobras','Amenorreia primária e secundária','Síndrome dos ovários policísticos','Neoplasias mamárias e rastreio','Incontinência urinária e distopias genitais','Climatério','Pré-natal de alto risco (Diabetes e Gemelaridade)','Prematuridade (Trabalho de parto prematuro, amniorr​​exe prematura)','Restrição de crescimento fetal intrauterino (CIUR)','Infecções na gestação (Toxoplasmose, Citomegalovirus, Rubéola, Herpes e Sífilis)','Modificações locais e sistêmicas no organismo materno na gravidez']],
    ['B', ['Anticoncepção','HPV, neoplasias cervicais e rastreio','Doença inflamatória pélvica','Sangramento Uterino Anormal','Endometriose','Vulvovaginites, cervicites (Cândidiase, tricomoníase, vaginose bacteriana, vaginite atrófica - incluir tratamento na gestante)','Infecções sexualmente transmissíveis ( sífilis, herpes genital, cancro mole, gonorreia, linfogranuloma venéreo, donovanose)','Síndromes hipertensivas da gestação (Pré-Eclâmpsia , Pré-Eclâmpsia superposta, Eclâmpsia, Hipertensão crônica e gestacional)','Vitalidade fetal - Cardiotocografia e ultrassonografias na gestação','Sangramentos de primeira metade da gestação (gravidez ectópica, gravidez molar, abortamento)','Sangramentos de segunda metade da gestação (descolamento prematuro de placenta, placenta prévia, rotura uterina, vasa prévia)','Puerpério']]
  ]],
  ['Pediatria', [
    ['A', ['Imunizações','Diarréia aguda e desidratação. Parasitose.','Aleitamento materno, introdução alimentar e alergia alimentar.','Infecções congênitas: toxoplasmose, rubéola, sífilis, citomegalovírus, herpes simples, Zika vírus.','Icterícia neonatal','Assistência ao recem nascido na sala de parto > ou igual a 34 semanas','Anafilaxia. Dermatite atópica.','Infecção de vias aéreas superiores','Doenças exantemáticas (Sarampo, Rubéola, Eritema infeccioso, Exantema súbito, Mononucleose infecciosa, Varicela, Escarlatina, Doença de Kawasaki, Síndrome mão pé boca)','Infecção do trato urinário','Crescimento e desenvolvimento da criança até 5 anos.','GNDA e Síndrome nefrótica.']],
    ['B', ['Suporte básico e Suporte avançado de vida','Asma na criança + rinite alérgica','Meningites e meningoencefalites','Convulsões na criança','Pneumonia adquirida na comunidade/ Bronquiolite','TDAH e autismo','Patologias dermatológicas: impetigo/ectima, erisipela/celulite, foliculite/furunculose, síndrome da pele escaldada, estrófulo, escabiose, Tinea, Pitiríase alba, Pitiríase Versicolor e Molusco.','Anemias: anemia ferropriva, anemia megaloblástica e falciforme','Sepse em pediatria.(Reconhecer SEPSE, entender os conceitos e abordagem)','Febre reumática.','Crescimento e desenvolvimento puberal do adolescente (fisiologia da puberdade normal, exame físico e estadiamento puberal, diferenciar desenvolvimento puberal fisiológico do patológico, baseado nas alterações clínicas e exames complementares, síndrome da adolescencia normal).Puberdade precoce.','Febre sem sinais localizatórios']]
  ]],
  ['Urgência e Emergência / Saúde Mental', [
    ['A', ['Suporte básico de vida e avançado: PALS e ACLS','Lesão renal aguda (Pré Renal, Renal e Pós Renal)','Psicopatologia e exame do estado mental- principais conceitos de psicopatologia, exame do estado mental, incluindo as manifestações clínicas nas principais desordens (esquizofrenia, transtornos afetivos e transtornos de ansiedade).','Sindrome respiratória aguda grave','Insuficiência respiratória (tipo I – hipoxêmica / tipo II – hipercápnica/ Mista)','Vias aéreas básica/ avançada (Extra glótica + Via aérea definitiva)','Cuidados paliativos e manejo da dor','Psicofarmacologia - antidepressivos (tricíclicos, inibidores da MAO, atípicos, moduladores de serotonina, Inibidores seletivos de recaptação de serotonina).','Emergências em Psiquiatria (tentativa de auto-extermínio, crise de ansiedade e surto psicótico)','Esquizofrenia e outros transtornos psicóticos (transtorno delirante, esquizoafetivo, psicótico)','Distúrbios do equilíbrio acidobásico','Intoxicações exógenas agudas']],
    ['B', ['Transtornos de Ansiedade (generalizada, pânico, fobias, TOC), Transtornos alimentares (bulimia, anorexia, compulsão)','Transtornos do humor (depressão maior, bipolar)','Choque septico e hipovolemico','Síndromes coronárianas agudas','Transtornos de personalidade (paranoide, esquizoide, antissocial, boderline, histriônica)','Insuficiencia cardíaca descompensada e Edema agudo pulmonar','Arritimias cardíacas','Transtornos mentais orgânicos (Delirium, Demência, Alzheimer, Parkinson)','Drogas vasoativas na urgência e emergência. Principais drogas vasoativas, Mecanismos de ação em receptores/doses/diluições, Vasopressores: Noradrenalina/Adrenalina/Vasopressina, Vasodilatadores:Nitroglicerina/Nitroprussiato de Sódio, Inotrópicos:Dobutamina/ Milrinone/ Levosimendan','Acidente com animais peçonhentos (ofídicos, aracnídeos, escorpiônicos) e Choque anafilático.','Cetoacidose diabética','AVE']]
  ]]
];

export function slugify(value) {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export const OSCE_MATRIX = groups.map(([name, themes], areaIndex) => ({
  name,
  slug: slugify(name),
  order: areaIndex + 1,
  active: true,
  themes: themes.map(([code, subthemes], themeIndex) => ({
    code,
    name: `Tema ${code}`,
    order: themeIndex + 1,
    active: true,
    // O identificador não depende do texto. Assim, correções ortográficas ou de
    // descrição atualizam o registro existente sem criar duplicatas.
    subthemes: subthemes.map((subtheme, index) => ({ name: subtheme, slug: `${code.toLowerCase()}-${index + 1}`, order: index + 1, active: true }))
  }))
}));

export const OSCE_FORMATS = ['ANAMNESE_FOCADA','EXAME_FISICO','RACIOCINIO_DIAGNOSTICO','CONDUTA','PROCEDIMENTO','COMUNICACAO','URGENCIA_EMERGENCIA','ESTACAO_COMPLETA'];

export function matrixCounts() {
  return OSCE_MATRIX.map(area => ({ area: area.name, themes: area.themes.map(theme => ({ code: theme.code, count: theme.subthemes.length })) }));
}
